// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCt9rNjWAhA0uAi4yccPN7R9TcOnVVSl0s',
    appId: '1:146441153644:web:3381bbdb26991abde5fc49',
    messagingSenderId: '146441153644',
    projectId: 'laza-d4570',
    authDomain: 'laza-d4570.firebaseapp.com',
    storageBucket: 'laza-d4570.firebasestorage.app',
    measurementId: 'G-ZZ3R840NXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCo_20fFNhUIM639U3567lr8rR6lK7-xYk',
    appId: '1:146441153644:android:8e1d8aba031192f8e5fc49',
    messagingSenderId: '146441153644',
    projectId: 'laza-d4570',
    storageBucket: 'laza-d4570.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaCTGvReJQQqjuwEcDr7_rx9hHnVUIYlc',
    appId: '1:146441153644:ios:2118b05bab6955bbe5fc49',
    messagingSenderId: '146441153644',
    projectId: 'laza-d4570',
    storageBucket: 'laza-d4570.firebasestorage.app',
    iosBundleId: 'com.example.laza',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaCTGvReJQQqjuwEcDr7_rx9hHnVUIYlc',
    appId: '1:146441153644:ios:2118b05bab6955bbe5fc49',
    messagingSenderId: '146441153644',
    projectId: 'laza-d4570',
    storageBucket: 'laza-d4570.firebasestorage.app',
    iosBundleId: 'com.example.laza',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCt9rNjWAhA0uAi4yccPN7R9TcOnVVSl0s',
    appId: '1:146441153644:web:89570680c9948ae5e5fc49',
    messagingSenderId: '146441153644',
    projectId: 'laza-d4570',
    authDomain: 'laza-d4570.firebaseapp.com',
    storageBucket: 'laza-d4570.firebasestorage.app',
    measurementId: 'G-X23VSCN2MV',
  );
}
